### PR TITLE
Add EtherNAT USB driver

### PR DESCRIPTION
**Pull request by DavidGZ**
Miro, I'm not 100% sure if I did it correctly, please extra check ;-)

### CODE REVIEW

**Comment by mikrosk** [comment]
Looks good to me. It would be nice if the usb loader could differentiate modules similar as xaloader.prg and mint.prg do. :)

**Comment by DavidGZ** [comment]
>Looks good to me. It would be nice if the usb loader could differentiate modules similar as xaloader.prg and mint.prg do. :)

OK, I'll take care of this as soon as I finish with what I'm doing now

**Comment by DavidGZ** [comment]
> > Looks good to me. It would be nice if the usb loader could differentiate modules similar as xaloader.prg and mint.prg do. :)
> 
> OK, I'll take care of this as soon as I finish with what I'm doing now

I've taken a look, USB loader already does, it chooses the modules after checking the _CPU cookie.

**Comment by mikrosk** [comment]
You are right - I'm not sure what I meant by that. Maybe I had a vague wish that also UCD/UDD modules respect that but it's not really that important.

**Pull request merged**
