### PR TITLE
Update new XaAES binaries directory

### PR DESCRIPTION
**Pull request by DavidGZ**
Miro, I don't find the script that makes the "old-school" package (trunk), so I didn't upgrade the new paths there.

### CODE REVIEW

**Comment by mikrosk** [comment]
There is no more old school builds - everything is built from `freemint-master` now. So as long you are happy with results, there is nothing more to change. :)

**Comment by mikrosk** [comment]
Btw when/if you are in mood, I have never been a fan of those `xaaes$TARGET.km` filenames, same for MINT$TARGET.PRG - it's in its own directory, so why not to name it just xaaes.km and mint.prg.

But that's completely optional and unnecessary in this PR, so merging.

**Comment by mikrosk** [comment]
@DavidGZ it seems to be failing for 68000: https://travis-ci.org/freemint/freemint/jobs/552097171#L4090

**Comment by DavidGZ** [comment]
> Btw when/if you are in mood, I have never been a fan of those `xaaes$TARGET.km` filenames, same for MINT$TARGET.PRG - it's in its own directory, so why not to name it just xaaes.km and mint.prg.

In fact I was tempted to do it, but I thought that perhaps someone find this useful, I was thinking in the ability from the XaAES loader to pick the right module depending on its name. I really don't have a strong opinion about it, so any decision is good for me. I'll move the discussion to the list just in case anybody has anything to say.

**Comment by DavidGZ** [comment]
> @DavidGZ it seems to be failing for 68000: https://travis-ci.org/freemint/freemint/jobs/552097171#L4090 and https://travis-ci.org/freemint/freemint/jobs/552097177#L4123
> 

Sorry for that, I have fixed it in my fork, I'm going to do a new pull-request. But the way, I never test my changes in these scripts before committing. Is there an easy way to do it locally?

> Also for usbtool.acc: https://travis-ci.org/freemint/freemint/jobs/552097181#L1565 ?

I don't understand this error, it seems that everything is right.

**Comment by mikrosk** [comment]
> I was thinking in the ability from the XaAES loader to pick the right module depending on its name

OK, that is a good point. Otherwise one would have to figure the proper name on his own.

**Comment by mikrosk** [comment]
> Is there an easy way to do it locally?

Because it is not very harmful (it is totally OK to do forced pushes in this repo) usually I'm equally lazy. ;) 

When I'm working on major changes, I fork this repo as well, enable travis builds for it (i.e. mikrosk/travis-scripts) (in _my_ travis settings, we are outside freemint now) and clone `mikrosk/travis-scripts` in `freemint` instead of `freemint/travis-scripts`. That's pretty much it.

Of course, then there is bintray but isn't important, build errors are.

**Comment by DavidGZ** [comment]
> > Also for usbtool.acc: https://travis-ci.org/freemint/freemint/jobs/552097181#L1565 ?
> 
> I don't understand this error, it seems that everything is right.

This still fails, let me look at it.

**Pull request merged**
